<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CoreMcp.Protocol\CoreMcp.Protocol.csproj" />
    <ProjectReference Include="..\..\src\CoreMcp.Tools\CoreMcp.Tools.csproj" />
  </ItemGroup>

</Project>
